### PR TITLE
fix: support nested fragment

### PR DESCRIPTION
**Pull request by sage-wen**
Nested fragment not work properly. for example:
<div v-frag>
    <div v-frag>
        <div id=“item”></div>
    </div>
</div>
Remove item div outer fragment cache has not update.

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks for the PR!

Can you provide a reproduction of the bug you're fixing or a failing test-case to help me understand what the problem is? (And to also prevent it from happening in the future.)

**Comment by sage-wen** [comment]
This is mine test demo.  If list update, try replace Inner Frag 
```
<template>
  <div>
    <ul>
      <Fragment ref="outerFrag">
        <component :is="fragment" ref="innerFrag">
          <Fragment>
            <li v-for="item in list" :key="item">{{item}}</li>
          </Fragment>
        </component>
      </Fragment>
    </ul>
    <div>
      <button @click="update">update list</button>
      <button @click="replace">replace Inner Frag</button>
    </div>
  </div>
</template>
<script>
import Fragment from './Fragment';
import Fragment2 from './Fragment2';

export default {
  components:{
    Fragment
  },
  data(){
    return {
      list: [1, 2],
      fragment: Fragment,
    }
  },
  methods: {
    update(){
      this.list.splice(0, 1, 3);//remove or replace first item
    },
    replace(){
      this.fragment = Fragment2;//update inner frag, outer frag Element $fakeChildren value is old and is removed on the document
    }
  }
}
</script>
```

**Comment by fuzi1996** [comment]
### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/vue-frag-forked-74ejz?file=/src/components/Example.vue)

**Comment by privatenumber** [comment]
This PR isn't mergeable since a lot of tests are failing.

I added a test to cover this case though here: https://github.com/privatenumber/vue-frag/compare/test-48?expand=1

Will try to find time for it soon.

**Comment by privatenumber** [comment]
Please try the latest version. It should be fixed.

Thanks for reporting!

**Pull request closed without merging**
